name: Bug report
description: Report a problem
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / output
      render: shell

  - type: input
    id: python
    attributes:
      label: Python version
      placeholder: "3.12.x"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: OS
      placeholder: "macOS 14 / Ubuntu 24.04 / Windows 11"
    validations:
      required: true
